import type { Product } from "./types";

const img = (id: string, alt: string): Product["images"][number] => ({
  url: `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=70`,
  alt,
  width: 900,
  height: 1125,
});

// Real product photography (sourced from the live cityglory.sk shop), used in
// place of the Unsplash placeholders for the homepage "obľúbené" strip.
const localImg = (path: string, alt: string, width: number, height: number): Product["images"][number] => ({
  url: path,
  alt,
  width,
  height,
});

// Standard apparel colourway — every "tricka" product offers just these two,
// so the colour filter on the category page stays a tight, adjacent pair.
const APPAREL_COLORS = [
  { name: "biela", hex: "#F8F8F8" },
  { name: "čierna", hex: "#2D2D2D" },
];

/**
 * Temporary mock catalogue used until the Shopify Storefront API is connected.
 * Replace `@/lib/shopify` data functions with real queries — these shapes match.
 *
 * Titles are plain product names (no "— category" suffix) — the category is
 * already obvious from context (page heading, category badge), so repeating
 * it in every title is redundant.
 */
export const mockProducts: Product[] = [
  {
    id: "gid://mock/Product/1",
    handle: "bratislava-modre-strechy-print",
    title: "Modré strechy",
    description:
      "Ilustrovaný pohľad na strechy bratislavského Starého Mesta. Tlač na archívnom papieri.",
    price: { amount: 29, currencyCode: "EUR" },
    images: [img("photo-1513635269975-59663e0ac1ad", "Modré strechy starého mesta")],
    category: "printy",
    city: "Bratislava",
    collection: "Staré Mesto",
    badges: ["novinka"],
    available: true,
  },
  {
    id: "gid://mock/Product/2",
    handle: "dunaj-magnetka",
    title: "Dunaj",
    description: "Keramická magnetka inšpirovaná zákrutami Dunaja.",
    price: { amount: 8, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Rieka Dunaj")],
    category: "magnetky",
    city: "Bratislava",
    available: true,
  },
  {
    id: "gid://mock/Product/3",
    handle: "kachlicka-secesia",
    title: "Secesia",
    description: "Ručne glazovaná kachlička s motívom secesnej fasády.",
    price: { amount: 18, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Secesná fasáda")],
    category: "kachlicky",
    city: "Bratislava",
    artist: "Mária K.",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/4",
    handle: "mesto-tricko",
    title: "Mesto",
    description: "Mäkké bavlnené tričko s minimalistickou potlačou panorámy.",
    price: { amount: 34, currencyCode: "EUR" },
    compareAtPrice: { amount: 39, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Panoráma mesta"),
      img("photo-1521572163474-6864f9cf17ab", "Mesto — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Mesto — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Silueta domova, ktorú spoznáte poslepiačky — veže, strechy a kopce Bratislavy zredukované na jednu čistú líniu. Nosíte tak mesto so sebou, nech ste kdekoľvek.",
    available: true,
  },
  {
    id: "gid://mock/Product/14",
    handle: "hrad-tricko",
    title: "Hrad",
    description:
      "Siluetu Bratislavského hradu sme premietli do jednoduchej, grafickej potlače. Limitovaná séria.",
    price: { amount: 36, currencyCode: "EUR" },
    images: [
      img("photo-1541849546-216549ae216d", "Bratislavský hrad"),
      img("photo-1521572163474-6864f9cf17ab", "Hrad — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Hrad — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["limitovane"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Biely hrad na kopci nad Dunajom je prvé, čo z mesta uvidíte zďaleka. Táto limitovaná séria vychádza zo siluety hradu tak, ako sa mení pri každom osvetlení — od denného kameňa po nočné zlato.",
    available: false,
  },
  {
    id: "gid://mock/Product/15",
    handle: "michalska-brana-tricko",
    title: "Michalská brána",
    description:
      "Jediná zachovaná mestská brána Bratislavy ako minimalistická línia na hrudi.",
    price: { amount: 32, currencyCode: "EUR" },
    compareAtPrice: { amount: 38, currencyCode: "EUR" },
    images: [
      img("photo-1519677100203-a0e668c92439", "Stredoveká brána"),
      img("photo-1521572163474-6864f9cf17ab", "Michalská brána — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Michalská brána — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    artist: "Mária K.",
    badges: ["capsula"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Michalská brána je jediná zachovaná mestská brána zo stredovekého opevnenia Bratislavy — cez jej oblúk prechádzali kupci, remeselníci aj kráľovské sprievody. Mária K. jej vežu premenila na minimalistickú líniu, ktorá si túto históriu nesie ďalej.",
    available: true,
  },
  {
    id: "gid://mock/Product/16",
    handle: "devin-tricko",
    title: "Devín",
    description:
      "Zrúcanina hradu na sútoku Dunaja a Moravy, vytlačená na strihu pre dámy.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1467269204594-9661b134dd2b", "Zrúcanina hradu nad riekou"),
      img("photo-1521572163474-6864f9cf17ab", "Devín — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Devín — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    colors: APPAREL_COLORS,
    audience: "damy",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Zrúcanina hradu na sútoku Dunaja a Moravy strážila hranicu už v časoch Veľkej Moravy. Devín je miesto, kam Bratislavčania chodia na výlety už generácie — a tento motív je pripomienkou, že história vie byť aj obyčajná nedeľná prechádzka.",
    available: true,
  },
  {
    id: "gid://mock/Product/17",
    handle: "slavin-tricko",
    title: "Slavín",
    description: "Tichý pamätník na kopci nad mestom, stvárnený jemnou grafickou skratkou.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1520175480921-4edfa2983e0f", "Pamätník na kopci"),
      img("photo-1521572163474-6864f9cf17ab", "Slavín — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Slavín — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["novinka"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Slavín na kopci nad Starým Mestom je jedno z najtichších miest v Bratislave — pamätník aj vyhliadka v jednom. Grafická skratka jeho obelisku pripomína, že aj pokoj má svoj tvar.",
    available: true,
  },
  {
    id: "gid://mock/Product/18",
    handle: "kamzik-tricko",
    title: "Kamzík",
    description: "Detský strih s hravou ilustráciou vysielača na Kamzíku.",
    price: { amount: 24, currencyCode: "EUR" },
    images: [
      img("photo-1499856871958-5b9627545d1a", "Lesnatý kopec s vežou"),
      img("photo-1521572163474-6864f9cf17ab", "Kamzík — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Kamzík — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    colors: APPAREL_COLORS,
    audience: "deti",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Vysielač na Kamzíku je bod, ktorý z Bratislavy vidno z diaľky — a z jeho vyhliadky zase vidno takmer celé mesto. Detský strih s hravou ilustráciou je pre malých budúcich výletníkov na lesnaté kopce nad mestom.",
    available: false,
  },
  {
    id: "gid://mock/Product/19",
    handle: "eurovea-tricko",
    title: "Eurovea",
    description: "Nábrežná silueta modernej štvrte, potlačená na mäkkej bavlne.",
    price: { amount: 36, currencyCode: "EUR" },
    compareAtPrice: { amount: 42, currencyCode: "EUR" },
    images: [
      img("photo-1543832923-44667a44c804", "Nábrežie s modernými budovami"),
      img("photo-1521572163474-6864f9cf17ab", "Eurovea — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Eurovea — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Nábrežie Eurovey je najmladšia tvár Bratislavy — tam, kde kedysi stáli továrne, dnes stoja sklenené fasády nad Dunajom. Tento motív je pripomienkou, že mesto sa mení a rastie, aj keď jeho rieka ostáva rovnaká.",
    available: true,
  },
  {
    id: "gid://mock/Product/5",
    handle: "pohladnica-noc",
    title: "Nočné mesto",
    description: "Pohľadnica s nočnou siluetou mesta a ručne písaným pozdravom.",
    price: { amount: 3, currencyCode: "EUR" },
    images: [img("photo-1480714378408-67cf0d13bc1b", "Nočné mesto")],
    category: "pohladnice",
    city: "Bratislava",
    available: true,
  },
  {
    id: "gid://mock/Product/6",
    handle: "taska-rieka",
    title: "Rieka",
    description: "Plátená taška s potlačou inšpirovanou riekou a mostami.",
    price: { amount: 22, currencyCode: "EUR" },
    images: [img("photo-1502602898657-3e91760cbb34", "Most cez rieku")],
    category: "tasky",
    city: "Bratislava",
    artist: "Mária K.",
    available: true,
  },
  {
    id: "gid://mock/Product/7",
    handle: "panorama-mikina",
    title: "Panoráma",
    description: "Mäkká mikina s vyšívaným motívom panorámy mesta.",
    price: { amount: 59, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Panoráma mesta")],
    category: "mikiny",
    city: "Bratislava",
    available: true,
  },
  {
    id: "gid://mock/Product/8",
    handle: "mestsky-erb-odznak",
    title: "Mestský erb",
    description: "Smaltovaný odznak s mestským motívom.",
    price: { amount: 6, currencyCode: "EUR" },
    images: [img("photo-1572635196237-14b3f281503f", "Detail smaltovaného odznaku")],
    category: "odznaky",
    city: "Bratislava",
    badges: ["novinka"],
    available: true,
  },
  {
    id: "gid://mock/Product/9",
    handle: "mestske-motivy-nalepky",
    title: "Mestské motívy",
    description: "Sada vinylových nálepiek s mestskými motívmi.",
    price: { amount: 5, currencyCode: "EUR" },
    images: [img("photo-1611532736597-de2d4265fba3", "Sada nálepiek")],
    category: "nalepky",
    city: "Bratislava",
    available: true,
  },
  // ── obľúbené (homepage favorites strip) ────────────────────────
  {
    id: "gid://mock/Product/10",
    handle: "korunovacne-klenoty-tricko",
    title: "Korunovačné klenoty",
    description:
      "Čierne unisex tričko s jemnou grafickou skratkou korunovačných klenotov, potlačené na mäkkej česanej bavlne. Strih je voľnejší, nezráža sa a dobre si drží tvar. Súčasť limitovanej edície inšpirovanej Bratislavským hradom.",
    price: { amount: 32, currencyCode: "EUR" },
    compareAtPrice: { amount: 39, currencyCode: "EUR" },
    images: [
      localImg("/products/korunovacne-klenoty-tricko.png", "Korunovačné klenoty — čierne tričko", 823, 823),
      img("photo-1521572163474-6864f9cf17ab", "Korunovačné klenoty — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Korunovačné klenoty — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    motif: "korunovacne-klenoty",
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Korunovačné klenoty putovali do Bratislavy spolu s uhorskými kráľmi — v Dóme svätého Martina ich za jedenásť storovaní nasadili jedenástim panovníkom. Tento motív si z nich požičiava len tú najkrajšiu časť: pocit, že aj vy si dnes môžete nasadiť korunu.",
    available: true,
  },
  {
    id: "gid://mock/Product/10-damske",
    handle: "korunovacne-klenoty-tricko-damske",
    title: "Korunovačné klenoty",
    description:
      "Tričko inšpirované korunovačnými klenotmi z Bratislavského hradu, v dámskom strihu.",
    price: { amount: 32, currencyCode: "EUR" },
    compareAtPrice: { amount: 39, currencyCode: "EUR" },
    images: [
      localImg("/products/korunovacne-klenoty-tricko-damske-real.png", "Korunovačné klenoty — čierne tričko, dámsky strih", 1000, 1000),
      img("photo-1521572163474-6864f9cf17ab", "Korunovačné klenoty — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Korunovačné klenoty — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["viral"],
    colors: [{ name: "čierna", hex: "#2D2D2D" }],
    audience: "damy",
    sizes: ["XS", "S", "M", "L", "XL"],
    motif: "korunovacne-klenoty",
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Korunovačné klenoty putovali do Bratislavy spolu s uhorskými kráľmi — v Dóme svätého Martina ich za jedenásť storovaní nasadili jedenástim panovníkom. Tento motív si z nich požičiava len tú najkrajšiu časť: pocit, že aj vy si dnes môžete nasadiť korunu.",
    available: true,
  },
  {
    id: "gid://mock/Product/10-panske",
    handle: "korunovacne-klenoty-tricko-panske",
    title: "Korunovačné klenoty",
    description:
      "Tričko inšpirované korunovačnými klenotmi z Bratislavského hradu, v pánskom strihu.",
    price: { amount: 32, currencyCode: "EUR" },
    compareAtPrice: { amount: 39, currencyCode: "EUR" },
    images: [
      localImg("/products/korunovacne-klenoty-tricko-panske-real.png", "Korunovačné klenoty — čierne tričko, pánsky strih", 1000, 1000),
      img("photo-1521572163474-6864f9cf17ab", "Korunovačné klenoty — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Korunovačné klenoty — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    badges: ["viral"],
    colors: [{ name: "čierna", hex: "#2D2D2D" }],
    audience: "panske",
    sizes: ["XS", "S", "M", "L", "XL"],
    motif: "korunovacne-klenoty",
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Korunovačné klenoty putovali do Bratislavy spolu s uhorskými kráľmi — v Dóme svätého Martina ich za jedenásť storovaní nasadili jedenástim panovníkom. Tento motív si z nich požičiava len tú najkrajšiu časť: pocit, že aj vy si dnes môžete nasadiť korunu.",
    available: true,
  },
  // ── tričká (prevzaté z cityglory.sk) ────────────────────────────
  {
    id: "gid://mock/Product/tr-beethoven-damske",
    handle: "beethoven-tricko-damske",
    title: "Beethoven",
    description: "Tričko s motívom Beethovena a jeho lásky k Bratislave, v dámskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/beethoven-tricko-damske.png", "Beethoven — tričko, dámsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "biela", hex: "#F8F8F8" }],
    audience: "damy",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Kráľ symfónií sa do Bratislavy vždy rád vracia. Vraj je z roka na rok krajšia a rozvinutejšia. Miluje jej atmosféru, ľudí a, samozrejme, aj zmrzlinu. Keď sa mu nechce tvoriť, dá si kopček — dva a je to! Zmrzlina ho dostane do tvorivého flow. Takto sa komponujú tie najkrajšie skladby. Jasný dôkaz, že aj klasika sa dá robiť s ľahkosťou a humorom.",
    available: true,
  },
  {
    id: "gid://mock/Product/tr-beethoven-panske",
    handle: "beethoven-tricko-panske",
    title: "Beethoven",
    description: "Tričko s motívom Beethovena a jeho lásky k Bratislave, v pánskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/beethoven-tricko-panske.png", "Beethoven — tričko, pánsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "biela", hex: "#F8F8F8" }],
    audience: "panske",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Kráľ symfónií sa do Bratislavy vždy rád vracia. Vraj je z roka na rok krajšia a rozvinutejšia. Miluje jej atmosféru, ľudí a, samozrejme, aj zmrzlinu. Keď sa mu nechce tvoriť, dá si kopček — dva a je to! Zmrzlina ho dostane do tvorivého flow. Takto sa komponujú tie najkrajšie skladby. Jasný dôkaz, že aj klasika sa dá robiť s ľahkosťou a humorom.",
    available: true,
  },
  {
    id: "gid://mock/Product/tr-subcarfly-damske",
    handle: "subcarfly-tricko-damske",
    title: "SUBCARFLY",
    description: "Tričko s motívom SUBCARFLY, v dámskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/subcarfly-tricko-damske.png", "SUBCARFLY — tričko, dámsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "biela", hex: "#F8F8F8" }],
    audience: "damy",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Bratislava má v porovnaní s inými hlavnými mestami najviac kreatívnych ľudí na počet obyvateľov. Práve preto vznikol Bratislavský inštitút technológií — v skratke BIT. Ten Massachusetský je síce známejší, ale u nás sa ladí na všetkých frekvenciách. Vynálezy sú natoľko prelomové, že zatiaľ pracuje v utajenom režime. SUBCARFLY je ponorka, auto a lietadlo v jednom. Nech sa páči, nastúpte a odvezte sa tam, kde fantázia nemá hranice.",
    available: true,
  },
  {
    id: "gid://mock/Product/tr-subcarfly-panske",
    handle: "subcarfly-tricko-panske",
    title: "SUBCARFLY",
    description: "Tričko s motívom SUBCARFLY, v pánskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/subcarfly-tricko-panske.png", "SUBCARFLY — tričko, pánsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "biela", hex: "#F8F8F8" }],
    audience: "panske",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Bratislava má v porovnaní s inými hlavnými mestami najviac kreatívnych ľudí na počet obyvateľov. Práve preto vznikol Bratislavský inštitút technológií — v skratke BIT. Ten Massachusetský je síce známejší, ale u nás sa ladí na všetkých frekvenciách. Vynálezy sú natoľko prelomové, že zatiaľ pracuje v utajenom režime. SUBCARFLY je ponorka, auto a lietadlo v jednom. Nech sa páči, nastúpte a odvezte sa tam, kde fantázia nemá hranice.",
    available: true,
  },
  {
    id: "gid://mock/Product/tr-ufo-damske",
    handle: "ufo-tricko-damske",
    title: "UFO",
    description: "Tričko s motívom bratislavského UFO mosta, v dámskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/ufo-tricko-damske.png", "UFO — tričko, dámsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "biela", hex: "#F8F8F8" }],
    audience: "damy",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Čarokrásna, romantická, nezabudnuteľná… Aj takáto je naša Bratislava. Či je to prežitá láska alebo pekný zážitok. Galantnosť je cnosť, ako balet v každodennom živote. Alebo ako UFO, ktoré sa vznáša nad Dunajom. Prečo tu je? Pretože Bratislava je taká pôvabná, že sa do nej zaľúbili aj mimozemšťania. Nechajte sa inšpirovať a zamilujte sa tiež.",
    available: true,
  },
  {
    id: "gid://mock/Product/tr-ufo-panske",
    handle: "ufo-tricko-panske",
    title: "UFO",
    description: "Tričko s motívom bratislavského UFO mosta, v pánskom strihu.",
    price: { amount: 25, currencyCode: "EUR" },
    images: [localImg("/products/ufo-tricko-panske.png", "UFO — tričko, pánsky strih", 1000, 1000)],
    category: "tricka",
    city: "Bratislava",
    colors: [{ name: "čierna", hex: "#2D2D2D" }],
    audience: "panske",
    sizes: ["XS", "S", "M", "L", "XL"],
    materialInfo:
      "100 % česaná bavlna, 180 g/m². Digitálna potlač, ktorá nepraská a nepustí farbu. Perte na 30 °C, naruby.",
    motifStory:
      "Čarokrásna, romantická, nezabudnuteľná… Aj takáto je naša Bratislava. Či je to prežitá láska alebo pekný zážitok. Galantnosť je cnosť, ako balet v každodennom živote. Alebo ako UFO, ktoré sa vznáša nad Dunajom. Prečo tu je? Pretože Bratislava je taká pôvabná, že sa do nej zaľúbili aj mimozemšťania. Nechajte sa inšpirovať a zamilujte sa tiež.",
    available: true,
  },
  {
    id: "gid://mock/Product/11",
    handle: "ufo-magnetka",
    title: "UFO",
    description: "Magnetka s motívom bratislavského UFO mostu.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [localImg("/products/ufo-magnetka.jpg", "UFO — magnetka", 617, 823)],
    category: "magnetky",
    city: "Bratislava",
    materialInfo:
      "Živicová magnetka na drevenom podklade s 3D efektom, oblé hrany, cca 6 × 8 cm. Silný magnet, ktorý bezpečne udrží aj hrubší papier.",
    motifStory:
      "Čarokrásna, romantická, nezabudnuteľná… Aj takáto je naša Bratislava. Či je to prežitá láska alebo pekný zážitok. Galantnosť je cnosť, ako balet v každodennom živote. Alebo ako UFO, ktoré sa vznáša nad Dunajom. Prečo tu je? Pretože Bratislava je taká pôvabná, že sa do nej zaľúbili aj mimozemšťania. Nechajte sa inšpirovať a zamilujte sa tiež.",
    available: true,
  },
  // ── magnetky (prevzaté z cityglory.sk) ──────────────────────────
  {
    id: "gid://mock/Product/mag-ufo-aktivne",
    handle: "ufo-aktivne-magnetka",
    title: "UFO — bolo vždy aktívne",
    description: "Magnetka s motívom mosta UFO a jeho tajnej vesmírnej minulosti.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/ufo-aktivne-magnetka.jpg", "UFO — bolo vždy aktívne — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Tajomstvo je konečne odhalené. Sovieti síce boli prví vo vesmíre a Američania na Mesiaci. No my vo vtedajšom Československu sme v Bratislave v roku 1972 dokončili nový most cez Dunaj s UFOm. Nebola to obyčajná stavba. Bol to vlastný vesmírny program s aktívnym lietajúcim tanierom. Výrazne nám v tom pomohli mimozemskí konštruktéri od Proxima Centauri, ako poďakovanie za záchranu ich posádky pri jednom z ich divokých pristátí. Zároveň sa na tom podieľali vtedajší špičkoví vedci zo štátneho podniku Tesla. Dôvodom prečo sa informácie dostávajú do sveta až teraz, je 50 rokov mlčanlivosti, ku ktorým sme sa zaviazali. Prestavba na aktívnu lietajúcu loď je podobná premene autobotov na konkrétnych transformerov. Cez deň je to reštaurácia, ale nenechajte sa zmiasť dokonalým maskovaním.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-bratislavsky-hrad",
    handle: "bratislavsky-hrad-magnetka",
    title: "Bratislavský hrad",
    description: "Magnetka s motívom Bratislavského hradu.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/bratislavsky-hrad-magnetka.jpg", "Bratislavský hrad — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Bratislavský hrad je špecifické miesto, ktoré je najlepšie navštíviť osobne. Nie je to totiž iba obyčajný hrad na kopci. Je to hrad magický, pretože priania, ktoré vyslovíte v areáli hradu sa Vám zvyknú vypĺňať. Na tomto mieste sa myšlienky svojou špeciálnou akceleráciou transformujú do postupného prevedenia. Najviac to funguje počas splnu, kedy sú energetické prúdy najsilnejšie. Háčik je v tom, že hlava a srdce, by spolu mali ladiť, byť v jednotnej frekvencii, prípadne stačí, ak priania vychádzajú priamo zo srdca, tie majú taktiež silnú vibráciu. Ako sa zvykne hovoriť, kým nevyskúšaš nevieš. Za návštevu magického hradu s vyslovením čarovných formuliek to rozhodne stojí.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-modry-kostolik",
    handle: "modry-kostolik-magnetka",
    title: "Modrý kostolík",
    description: "Magnetka s motívom Modrého kostolíka svätej Alžbety.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/modry-kostolik-magnetka.jpg", "Modrý kostolík — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Vedeli ste, že pôvodne mal kostol žltú farbu? Súčasnú modrú farbu dosiahol počas opravy po druhej svetovej vojne, počas ktorej došlo k miernemu poškodeniu. Architektom modrého kostolíka bol budapeštiansky architekt Edmund Lechner, vďaka ktorému je tento secesný skvost vysoko vyhľadávaným objektom nielen pre uzatváranie cirkevných sobášov. Základný kameň bol položený v roku 1909 a venovaný bol sv. Alžbete, dcére uhorského kráľa Ondreja II, ktorá sa narodila v roku 1207 na Bratislavskom hrade. Kostolík sa stal jedným zo symbolov mesta Bratislavy, zobrazený je aj ako symbol Slovenska v Mini-Európa parku v Bruseli. Priestorový zážitok umocní aj návšteva interiéru, ktorý nevie vyvolať žiadna zhotovená fotografia. Svojho času bola stavba v časovom sklze oproti pôvodným plánom výstavby. Keď ho vtedajšie ministerstvo poháňalo, Lechnerova legendárna veta znela: „Umenie nemožno súriť.“ S odstupom času mu dávame za pravdu. To vtedajšie čakanie, vyvažujú šikovné ruky majstrov, ktorí sa podpísali pod jedinečné architektonické dielo. Ďakujeme za to.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-kaviaren-stefanka",
    handle: "kaviaren-stefanka-magnetka",
    title: "Kaviareň Štefánka",
    description: "Magnetka s motívom legendárnej Kaviarne Štefánka.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/kaviaren-stefanka-magnetka.jpg", "Kaviareň Štefánka — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Legendárna kaviareň bola založená v roku 1897. Jej prvou majiteľkou bola Rosa Dresdner, ktorá si priestory nárožného domu prenajala od grófky Irmy Erdódyovej. Grófka iste mala podnikateľské nadanie, nakoľko keď bol postavený Grasalkovičov palác, okolité parcely sa stali vychyteným a žiadaným priestorom. A tak v miestach, kde rástli vinice, vznikali honosné paláce a vily aristokracie. Grófka Irma Erdódyová medzi prvými odkúpila parcelu oproti Grasalkovičovmu palácu a dala tak podnet na vznik lukratívnej časti mesta, ktorá nesie názov Palisády. Kaviareň Štefánia sa hneď zaradila medzi najobľúbenejšie vo vtedajšom Prešporku. Jej povesť a prestíž neutrpela ani striedaním majiteľov, nakoľko každý z nich sem vniesol punc osobitosti, elegancie, secesnej noblesy a tiež neodmysliteľného fluida, ktoré sem vnášali návštevníci z bohémskeho prostredia — umelci, spisovatelia, výtvarníci, básnici, ale tiež lekári, právnici a ďalší významní predstavitelia z radov intelektuálov. Má svoje čaro i dnes. Zo zrekonštruovaných priestorov na vás dýchne atmosféra monarchistickej noblesy a ak máte okrem kávy, zákuskov a výbornej kuchyne chuť aj na niečo extra, ste tu správne. Dostanete tu slimáky a la princezná Štefánia, ktoré boli jej pochúťkou, a nezabudnite ochutnať ďalšiu gastronomickú špecialitu majiteľov kaviarne — bratislavské krevety.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-slovenske-narodne-divadlo",
    handle: "snd-magnetka",
    title: "Slovenské národné divadlo",
    description: "Magnetka s motívom Slovenského národného divadla.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/snd-magnetka.jpg", "Slovenské národné divadlo — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Slovenské národné divadlo je významná kultúrna pamiatka a aktívna divadelná scéna. Navrhli ho, ako aj ďalších 45 divadiel po celej Európe, viedenskí architekti Ferdinand Fellner a Hermann Helmer. Vďaka schopnosti vytvárať umenie získavame ako ľudia punc originality vo svete tvorstva na tejto planéte. Poctivé nácviky divadelných predstavení živými hercami sú tu s nami stovky rokov a dlho tu aj ostanú. Hodiny príprav a ladenia postupne vylepšujú finálne divadelné diela do podôb, na ktoré si spomíname často aj po rokoch, nakoľko sila zápisu do archívov našich hláv je vďaka hudbe, pohybu, kostýmom, kulisám, emóciám, dialógom, jednoducho viacdimenzionálnemu zážitku, jedinečná. Umenie zušľachťuje, pretože nám otvára nové dvere zážitkov, ktoré v nás zanechávajú stopu vedomia, že človek okrem fascinujúcich stavieb a vynálezov dokáže vytvárať veľkolepé predstavenia, ktoré nás kultivujú rovnako tak, ako nás udivujú umelci svojimi výkonmi.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-kamzik",
    handle: "kamzik-portal-magnetka",
    title: "Kamzík — vesmírny cestovateľský portál",
    description: "Magnetka s motívom televíznej veže Kamzík.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/kamzik-portal-magnetka.jpg", "Kamzík — vesmírny cestovateľský portál — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Začiatok pohoria Karpát, pomerne silné magnetické pole, ale aj dobré diplomatické vzťahy medzi mimozemskými návštevníkmi dali základ pre vytvorenie prvého vesmírneho portálu. Samozrejme bez dominantnej stavby, dosahujúcej výšku 194 m, ktorá aktívne slúži aj ako televízna veža, by to nešlo. Jedným vytváraným oblúkom odlietajú a druhým prilietajú mimozemské lode rôznych konštrukcií a tvarov. Nevieme to zachytiť voľným okom, aktuálne iba špeciálnym prístrojom, ktorý vytvoril Bratislavský inštitút technológií, BIT. Zabudnite na najkrajšie autá aké poznáte, toto je iná liga. Veža Kamzík bola postavená v roku 1975 vo výške 433 m n. m. Vo veži sa v 70 m výške nachádza reštaurácia Veža a vyhliadková plošina s výhľadom na Bratislavu. Veža je jedným zo symbolov a orientačným bodom hlavného mesta.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-brat-i-slava",
    handle: "brat-i-slava-magnetka",
    title: "Brat i Slava",
    description: "Magnetka s motívom legendy o založení Bratislavy.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/brat-i-slava-magnetka.jpg", "Brat i Slava — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Legenda hovorí, že raz dávno, počas putovania obchodných karaván, sa na tomto území stretli dvaja mladí ľudia. Bola to láska na prvý pohľad. Brat bol dobrosrdečný a mužný, Slava zase krásna a inteligentná. Spoločne ostali žiť na križovatke ciest v srdci Európy. Ideálna poloha, k tomu blízkosť rieky Dunaj, prilákala aj ďalších osadníkov a z malého sídla postupne vzniklo prosperujúce mesto. Na počesť jeho zakladateľov dostalo názov BratiSlava.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-korunovacne-klenoty",
    handle: "korunovacne-klenoty-magnetka",
    title: "Korunovačné klenoty",
    description: "Magnetka s motívom korunovačných klenotov.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/korunovacne-klenoty-magnetka.jpg", "Korunovačné klenoty — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Bratislava je taktiež historické korunovačné mesto. Každý sme kráľom a kráľovnou vo vlastnom svete. Byť na vrchole znamená aj niesť so sebou zodpovednosť. Nech je tento motív zároveň aj impulzom pre osobné napredovanie a nech robí radosť ľuďom navôkol. Sláva je večná, ak je zaslúžená! Toto mesto má v sebe niečo magické, čo ľudí inšpiruje k dosiahnutiu veľkých vecí.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-metro",
    handle: "metro-magnetka",
    title: "METRO Bratislava",
    description: "Magnetka s motívom bratislavského metra.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/metro-magnetka.jpg", "METRO Bratislava — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Tak sme sa dočkali — Bratislava má vlastné metro! Naplnili sa všetky očakávania: doprava v meste je výrazne odbremenená, znížilo sa množstvo emisií vo vzduchu a zlepšila sa kvalita života. Na počesť tejto historickej udalosti uvádzame celoročný bezplatný lístok na naše Bratislavské metro. Ukončite nástup a výstup — dvere sa zatvárajú.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-casostroj",
    handle: "casostroj-magnetka",
    title: "Časostroj",
    description: "Magnetka s motívom časostroja.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/casostroj-magnetka.jpg", "Časostroj — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "A sme opäť bližšie k výroku „nič nie je nemožné“. Cestovanie do minulosti pomocou časostroja sa stáva realitou. Opraviť si zlú známku v škole? Podať výherné čísla v lotérii? Stretnúť sa so sebou samým v detstve? Vymyslite si vlastný spôsob, akým zmeníte minulosť. Je tu však malý háčik — verzia číslo 1 je v testovaní. Pár vecičiek sa nám z minulosti už nevrátilo. Pozývame odvážlivcov na testovacie jazdy časostrojom.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-univerzita-stastia",
    handle: "univerzita-stastia-magnetka",
    title: "Svetová Univerzita Šťastia",
    description: "Magnetka s motívom Svetovej univerzity šťastia.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/univerzita-stastia-magnetka.jpg", "Svetová Univerzita Šťastia — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Táto univerzita založená v roku 2020 je prvá svojho druhu na svete. Bola založená v Bratislave v spolupráci s Bhutánskym úradom pre meranie šťastia obyvateľov krajiny. A prečo práve v Bratislave? Pretože tu sa srdcia spájajú v srdci Európy. Na tomto mieste sa rozum a srdce navzájom podporujú. Pridajte sa do klubu študentov a sympatizantov tejto univerzity. Staňte sa súčasťou komunity ľudí, ktorí chcú zmeniť svet na šťastnejšie miesto. Možnosť aj dištančného štúdia odkiaľkoľvek na svete.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-slovensky-rozhlas",
    handle: "slovensky-rozhlas-magnetka",
    title: "Slovenský Rozhlas",
    description: "Magnetka s motívom budovy Slovenského rozhlasu.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/slovensky-rozhlas-magnetka.jpg", "Slovenský Rozhlas — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Všetci občas potrebujeme zmenu, aby sme prišli na iné myšlienky. V tomto prípade sa želanie plní — kamoši od Proxima Centauri vás zoberú na trip. Nemusíte ani chodiť k Slovenskému rozhlasu. Touto grafikou dávate jasný signál, že ste ready na cestu po galaxii. Oni si vás vyzdvihnú. Prajeme vám nezabudnuteľnú jazdu!",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-subcarfly",
    handle: "subcarfly-magnetka",
    title: "SUBCARFLY",
    description: "Magnetka s motívom SUBCARFLY — ponorky, auta a lietadla v jednom.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/subcarfly-magnetka.jpg", "SUBCARFLY — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Bratislava má v porovnaní s inými hlavnými mestami najviac kreatívnych ľudí na počet obyvateľov. Práve preto vznikol Bratislavský inštitút technológií — v skratke BIT. Ten Massachusetský je síce známejší, ale u nás sa ladí na všetkých frekvenciách. Vynálezy sú natoľko prelomové, že zatiaľ pracuje v utajenom režime. SUBCARFLY je ponorka, auto a lietadlo v jednom. Nech sa páči, nastúpte a odvezte sa tam, kde fantázia nemá hranice.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-maria-terezia",
    handle: "maria-terezia-magnetka",
    title: "Mária Terézia",
    description: "Magnetka s motívom Márie Terézie.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/maria-terezia-magnetka.jpg", "Mária Terézia — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Školáci hovoria: „To je tá, čo zaviedla povinnú školskú dochádzku — sorry, s tou sa nekamarátime.“ Na druhej strane upratala, pozdvihla a zmodernizovala celú monarchiu, takže na miske váh nie je o čom. Ale hlavne mala úprimne rada Bratislavu, ktorú pomohla vytiahnuť do klubu dôležitých miest. Dokonca ešte o niečo viac ako svoju obľúbenú čokoládu. Takže ak máte radi čokoládu, máte radi aj Bratislavu. A ak máte radi Bratislavu, máte radi aj Máriu Teréziu.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-hviezdoslav",
    handle: "hviezdoslav-magnetka",
    title: "Hviezdy Slávil",
    description: "Magnetka s motívom básnika Pavla Országha Hviezdoslava.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/hviezdoslav-magnetka.jpg", "Hviezdy Slávil — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Pavol Országh Hviezdoslav patrí medzi najvýznamnejších slovenských básnikov. Miloval hviezdy na oblohe tak, že sa s nimi snažil prepájať ako to len išlo. Aj preto začal používať priezvisko Hviezdoslav, s ktorým následne kráčal po celý zvyšok života. Ten, ktorý slávil hviezdy, cítil, že to čo je hore presahuje nás samotných, a zároveň, že aj my sme súčasťou tohto vesmírneho orchestra. Esenciu svojho bytia vnášal do tvorby, ktorá sa postupne rodila z jeho pera. Hviezdoslavova tvorba je oslavou života v jeho rôznych podobách. Ako hviezdy na nočnej oblohe, osvetľovala cestu ľuďom a ukazovala im krásu a hlbší zmysel života. Sláviť hviezdy ich hladením po oblohe našimi očami je podobný zázrak ako život sám o sebe, s rovnakou možnosťou postupného objavovania nepoznaného.",
    available: true,
  },
  {
    id: "gid://mock/Product/mag-beethoven",
    handle: "beethoven-magnetka",
    title: "Beethoven",
    description: "Magnetka s motívom Beethovena a jeho lásky k Bratislave.",
    price: { amount: 4, currencyCode: "EUR" },
    images: [localImg("/products/beethoven-magnetka.jpg", "Beethoven — magnetka", 1000, 1000)],
    category: "magnetky",
    city: "Bratislava",
    motifStory:
      "Kráľ symfónií sa do Bratislavy vždy rád vracia. Vraj je z roka na rok krajšia a rozvinutejšia. Miluje jej atmosféru, ľudí a, samozrejme, aj zmrzlinu. Keď sa mu nechce tvoriť, dá si kopček — dva a je to! Zmrzlina ho dostane do tvorivého flow. Takto sa komponujú tie najkrajšie skladby. Jasný dôkaz, že aj klasika sa dá robiť s ľahkosťou a humorom.",
    available: true,
  },
  {
    id: "gid://mock/Product/12",
    handle: "modry-kostolik-kachlicka",
    title: "Modrý kostolík",
    description: "Ručne glazovaná kachlička s motívom Modrého kostolíka.",
    price: { amount: 19, currencyCode: "EUR" },
    images: [localImg("/products/modry-kostolik-kachlicka.jpg", "Modrý kostolík — kachlička", 700, 700)],
    category: "kachlicky",
    city: "Bratislava",
    motifStory:
      "Vedeli ste, že pôvodne mal kostol žltú farbu? Súčasnú modrú farbu dosiahol počas opravy po druhej svetovej vojne, počas ktorej došlo k miernemu poškodeniu. Architektom modrého kostolíka bol budapeštiansky architekt Edmund Lechner, vďaka ktorému je tento secesný skvost vysoko vyhľadávaným objektom nielen pre uzatváranie cirkevných sobášov. Základný kameň bol položený v roku 1909 a venovaný bol sv. Alžbete, dcére uhorského kráľa Ondreja II, ktorá sa narodila v roku 1207 na Bratislavskom hrade. Kostolík sa stal jedným zo symbolov mesta Bratislavy, zobrazený je aj ako symbol Slovenska v Mini-Európa parku v Bruseli. Priestorový zážitok umocní aj návšteva interiéru, ktorý nevie vyvolať žiadna zhotovená fotografia. Svojho času bola stavba v časovom sklze oproti pôvodným plánom výstavby. Keď ho vtedajšie ministerstvo poháňalo, Lechnerova legendárna veta znela: „Umenie nemožno súriť.“ S odstupom času mu dávame za pravdu. To vtedajšie čakanie, vyvažujú šikovné ruky majstrov, ktorí sa podpísali pod jedinečné architektonické dielo. Ďakujeme za to.",
    available: true,
  },
  {
    id: "gid://mock/Product/13",
    handle: "fajnorka-print",
    title: "Fajnorka",
    description: "Ilustrovaný print inšpirovaný bratislavskou štvrťou Fajnorovo.",
    price: { amount: 27, currencyCode: "EUR" },
    images: [localImg("/products/fajnorka-print.jpg", "Fajnorovo nábrežie, Bratislava", 525, 700)],
    category: "printy",
    city: "Bratislava",
    badges: ["novinka"],
    available: true,
  },
  // ── capsula (limited artist collaborations) ────────────────────
  {
    id: "gid://mock/Product/20",
    handle: "sadovska-vlny-magnetka",
    title: "Vlny",
    description: "Magnetka s maliarskym motívom inšpirovaným Dunajom.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Vlny — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    artist: "Dorota Sadovská",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/21",
    handle: "sadovska-vlny-tricko",
    title: "Vlny",
    description: "Tričko s maliarskym motívom Doroty Sadovskej.",
    price: { amount: 36, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Vlny — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Vlny — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Vlny — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    artist: "Dorota Sadovská",
    badges: ["capsula"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/22",
    handle: "sadovska-vlny-mikina",
    title: "Vlny",
    description: "Mikina s maliarskym motívom Doroty Sadovskej.",
    price: { amount: 62, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Vlny — mikina")],
    category: "mikiny",
    city: "Bratislava",
    artist: "Dorota Sadovská",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/23",
    handle: "sadovska-vlny-kachlicka",
    title: "Vlny",
    description: "Ručne glazovaná kachlička s maliarskym motívom Doroty Sadovskej.",
    price: { amount: 22, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Vlny — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    artist: "Dorota Sadovská",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/24",
    handle: "ormandik-torzo-magnetka",
    title: "Torzo",
    description: "Magnetka so sochárskym motívom Mareka Ormandíka.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Torzo — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    artist: "Marek Ormandík",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/25",
    handle: "ormandik-torzo-tricko",
    title: "Torzo",
    description: "Tričko so sochárskym motívom Mareka Ormandíka.",
    price: { amount: 36, currencyCode: "EUR" },
    images: [
      img("photo-1541849546-216549ae216d", "Torzo — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Torzo — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Torzo — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    artist: "Marek Ormandík",
    badges: ["capsula"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/26",
    handle: "ormandik-torzo-mikina",
    title: "Torzo",
    description: "Mikina so sochárskym motívom Mareka Ormandíka.",
    price: { amount: 62, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Torzo — mikina")],
    category: "mikiny",
    city: "Bratislava",
    artist: "Marek Ormandík",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/27",
    handle: "ormandik-torzo-kachlicka",
    title: "Torzo",
    description: "Ručne glazovaná kachlička so sochárskym motívom Mareka Ormandíka.",
    price: { amount: 22, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Torzo — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    artist: "Marek Ormandík",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/28",
    handle: "vinczeova-reflektor-magnetka",
    title: "Reflektor",
    description: "Magnetka s motívom inšpirovaným Adelou Vinczeovou.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Reflektor — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    artist: "Adela Vinczeová",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/29",
    handle: "vinczeova-reflektor-tricko",
    title: "Reflektor",
    description: "Tričko s motívom inšpirovaným Adelou Vinczeovou.",
    price: { amount: 36, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Reflektor — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Reflektor — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Reflektor — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    artist: "Adela Vinczeová",
    badges: ["capsula"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/30",
    handle: "vinczeova-reflektor-mikina",
    title: "Reflektor",
    description: "Mikina s motívom inšpirovaným Adelou Vinczeovou.",
    price: { amount: 62, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Reflektor — mikina")],
    category: "mikiny",
    city: "Bratislava",
    artist: "Adela Vinczeová",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/31",
    handle: "vinczeova-reflektor-kachlicka",
    title: "Reflektor",
    description: "Ručne glazovaná kachlička s motívom inšpirovaným Adelou Vinczeovou.",
    price: { amount: 22, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Reflektor — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    artist: "Adela Vinczeová",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/32",
    handle: "ivan-opona-magnetka",
    title: "Opona",
    description: "Magnetka s divadelným motívom inšpirovaným Zdenkom Ivanom.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Opona — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    artist: "Zdenko Ivan",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/33",
    handle: "ivan-opona-tricko",
    title: "Opona",
    description: "Tričko s divadelným motívom inšpirovaným Zdenkom Ivanom.",
    price: { amount: 36, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Opona — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Opona — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Opona — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    artist: "Zdenko Ivan",
    badges: ["capsula"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/34",
    handle: "ivan-opona-mikina",
    title: "Opona",
    description: "Mikina s divadelným motívom inšpirovaným Zdenkom Ivanom.",
    price: { amount: 62, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Opona — mikina")],
    category: "mikiny",
    city: "Bratislava",
    artist: "Zdenko Ivan",
    badges: ["capsula"],
    available: true,
  },
  {
    id: "gid://mock/Product/35",
    handle: "ivan-opona-kachlicka",
    title: "Opona",
    description: "Ručne glazovaná kachlička s divadelným motívom inšpirovaným Zdenkom Ivanom.",
    price: { amount: 22, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Opona — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    artist: "Zdenko Ivan",
    badges: ["capsula"],
    available: true,
  },
  // ── viral (limited drops reacting to trends & cultural moments) ────
  {
    id: "gid://mock/Product/40",
    handle: "cumil-magnetka",
    title: "Čumil",
    description: "Magnetka s motívom bratislavského Čumila.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Čumil — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    collection: "Čumil",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/41",
    handle: "cumil-tricko",
    title: "Čumil",
    description: "Tričko s motívom bratislavského Čumila.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Čumil — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Čumil — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Čumil — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    collection: "Čumil",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/42",
    handle: "cumil-mikina",
    title: "Čumil",
    description: "Mikina s motívom bratislavského Čumila.",
    price: { amount: 59, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Čumil — mikina")],
    category: "mikiny",
    city: "Bratislava",
    collection: "Čumil",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/43",
    handle: "cumil-kachlicka",
    title: "Čumil",
    description: "Ručne glazovaná kachlička s motívom bratislavského Čumila.",
    price: { amount: 19, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Čumil — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    collection: "Čumil",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/44",
    handle: "prvy-sneh-magnetka",
    title: "Prvý sneh",
    description: "Magnetka s motívom zasneženého Starého Mesta.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Prvý sneh — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    collection: "Prvý sneh",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/45",
    handle: "prvy-sneh-tricko",
    title: "Prvý sneh",
    description: "Tričko s motívom zasneženého Starého Mesta.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Prvý sneh — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Prvý sneh — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Prvý sneh — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    collection: "Prvý sneh",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/46",
    handle: "prvy-sneh-mikina",
    title: "Prvý sneh",
    description: "Mikina s motívom zasneženého Starého Mesta.",
    price: { amount: 59, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Prvý sneh — mikina")],
    category: "mikiny",
    city: "Bratislava",
    collection: "Prvý sneh",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/47",
    handle: "prvy-sneh-kachlicka",
    title: "Prvý sneh",
    description: "Ručne glazovaná kachlička s motívom zasneženého Starého Mesta.",
    price: { amount: 19, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Prvý sneh — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    collection: "Prvý sneh",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/48",
    handle: "halusky-magnetka",
    title: "Halušky",
    description: "Magnetka s motívom bryndzových halušiek.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Halušky — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    collection: "Halušky",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/49",
    handle: "halusky-tricko",
    title: "Halušky",
    description: "Tričko s motívom bryndzových halušiek.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Halušky — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Halušky — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Halušky — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    collection: "Halušky",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/50",
    handle: "halusky-mikina",
    title: "Halušky",
    description: "Mikina s motívom bryndzových halušiek.",
    price: { amount: 59, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Halušky — mikina")],
    category: "mikiny",
    city: "Bratislava",
    collection: "Halušky",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/51",
    handle: "halusky-kachlicka",
    title: "Halušky",
    description: "Ručne glazovaná kachlička s motívom bryndzových halušiek.",
    price: { amount: 19, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Halušky — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    collection: "Halušky",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/52",
    handle: "silvester-magnetka",
    title: "Silvester",
    description: "Magnetka s motívom novoročného ohňostroja nad mestom.",
    price: { amount: 9, currencyCode: "EUR" },
    images: [img("photo-1518005020951-eccb494ad742", "Silvester — magnetka")],
    category: "magnetky",
    city: "Bratislava",
    collection: "Silvester",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/53",
    handle: "silvester-tricko",
    title: "Silvester",
    description: "Tričko s motívom novoročného ohňostroja nad mestom.",
    price: { amount: 34, currencyCode: "EUR" },
    images: [
      img("photo-1449824913935-59a10b8d2000", "Silvester — tričko"),
      img("photo-1521572163474-6864f9cf17ab", "Silvester — detail potlače"),
      img("photo-1503341504253-dff4815485f1", "Silvester — nosené tričko"),
    ],
    category: "tricka",
    city: "Bratislava",
    collection: "Silvester",
    badges: ["viral"],
    colors: APPAREL_COLORS,
    audience: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
  },
  {
    id: "gid://mock/Product/54",
    handle: "silvester-mikina",
    title: "Silvester",
    description: "Mikina s motívom novoročného ohňostroja nad mestom.",
    price: { amount: 59, currencyCode: "EUR" },
    images: [img("photo-1556821840-3a63f95609a7", "Silvester — mikina")],
    category: "mikiny",
    city: "Bratislava",
    collection: "Silvester",
    badges: ["viral"],
    available: true,
  },
  {
    id: "gid://mock/Product/55",
    handle: "silvester-kachlicka",
    title: "Silvester",
    description: "Ručne glazovaná kachlička s motívom novoročného ohňostroja nad mestom.",
    price: { amount: 19, currencyCode: "EUR" },
    images: [img("photo-1496564203457-11bb12075d90", "Silvester — kachlička")],
    category: "kachlicky",
    city: "Bratislava",
    collection: "Silvester",
    badges: ["viral"],
    available: true,
  },
];
